#!/bin/bash


# slideshow requires feh to be installed

#sleep script to give pie desktop time to load USB after boot
sleep 30
# get day of week store in DOW variable
DOW=$(date +%u);

case $DOW in
			1)
				feh /media/pi/AndrewUSB/Pictures/family --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			2)
				feh /media/pi/AndrewUSB/Pictures/KatiePictures --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			3)
				feh /media/pi/AndrewUSB/Pictures/family --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			4)
				feh /media/pi/AndrewUSB/Pictures/Katie_and_drew_adventures --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			5)
				feh /media/pi/AndrewUSB/Pictures/family --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			6)
				feh /media/pi/AndrewUSB/Pictures/mompictures --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
			7)
				feh /media/pi/AndrewUSB/Pictures/Katie_and_drew_adventures --recursive --fullscreen --auto-zoom --slideshow-delay 5 --image-bg black --hide-pointer --auto-rotate;;
esac